[package]
name = "stage2_rust"
version = "0.1.0"
edition = "2024"

[dependencies]

[profile.dev]
panic = "abort"
lto = false
opt-level = 0

[profile.release]
panic = "abort"
lto = true
opt-level = "z"
