[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

[dependencies]
kernel-shared = { path = "../kernel-shared" }
elf = { version = "0.7.4", default-features = false }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
