[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

[dependencies]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
#opt-level = 0
#lto = true
#codegen-units = 1
#strip = "debuginfo"
