[package]
name = "kernel"
version = "0.1.0"
edition = "2024"

[dependencies]
kernel-shared = { path = "../kernel-shared" }

[patch.crates-io]
portable-atomic = { path = "../../portableAtomic" }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
